version: "3.8"
services:
  backend:
    build: ./backend/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/aura_db
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aura_db
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
